{
 "title": "http",
 "tags": [ "built-with-weaver" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Number of active HTTP requests.",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(http.client.active_requests)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "The duration of the successfully established outbound HTTP connections.",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(http.client.connection.duration_bucket[$__rate_interval]))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, rate(http.client.connection.duration_bucket[$__rate_interval]))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, rate(http.client.connection.duration_bucket[$__rate_interval]))",
     "legendFormat": "p50"
    },
    {
     "expr": "rate(http.client.connection.duration_sum[$__rate_interval]) / rate(http.client.connection.duration_count[$__rate_interval])",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "Number of outbound HTTP connections that are currently active or idle on the client.",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(http.client.open_connections)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Size of HTTP client request bodies.",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(http.client.request.body.size_bucket[$__rate_interval]))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, rate(http.client.request.body.size_bucket[$__rate_interval]))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, rate(http.client.request.body.size_bucket[$__rate_interval]))",
     "legendFormat": "p50"
    },
    {
     "expr": "rate(http.client.request.body.size_sum[$__rate_interval]) / rate(http.client.request.body.size_count[$__rate_interval])",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "Duration of HTTP client requests.",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(http.client.request.duration_bucket[$__rate_interval]))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, rate(http.client.request.duration_bucket[$__rate_interval]))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, rate(http.client.request.duration_bucket[$__rate_interval]))",
     "legendFormat": "p50"
    },
    {
     "expr": "rate(http.client.request.duration_sum[$__rate_interval]) / rate(http.client.request.duration_count[$__rate_interval])",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "Size of HTTP client response bodies.",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(http.client.response.body.size_bucket[$__rate_interval]))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, rate(http.client.response.body.size_bucket[$__rate_interval]))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, rate(http.client.response.body.size_bucket[$__rate_interval]))",
     "legendFormat": "p50"
    },
    {
     "expr": "rate(http.client.response.body.size_sum[$__rate_interval]) / rate(http.client.response.body.size_count[$__rate_interval])",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "Number of active HTTP server requests.",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(http.server.active_requests)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Size of HTTP server request bodies.",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(http.server.request.body.size_bucket[$__rate_interval]))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, rate(http.server.request.body.size_bucket[$__rate_interval]))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, rate(http.server.request.body.size_bucket[$__rate_interval]))",
     "legendFormat": "p50"
    },
    {
     "expr": "rate(http.server.request.body.size_sum[$__rate_interval]) / rate(http.server.request.body.size_count[$__rate_interval])",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "Duration of HTTP server requests.",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(http.server.request.duration_bucket[$__rate_interval]))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, rate(http.server.request.duration_bucket[$__rate_interval]))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, rate(http.server.request.duration_bucket[$__rate_interval]))",
     "legendFormat": "p50"
    },
    {
     "expr": "rate(http.server.request.duration_sum[$__rate_interval]) / rate(http.server.request.duration_count[$__rate_interval])",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "Size of HTTP server response bodies.",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(http.server.response.body.size_bucket[$__rate_interval]))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, rate(http.server.response.body.size_bucket[$__rate_interval]))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, rate(http.server.response.body.size_bucket[$__rate_interval]))",
     "legendFormat": "p50"
    },
    {
     "expr": "rate(http.server.response.body.size_sum[$__rate_interval]) / rate(http.server.response.body.size_count[$__rate_interval])",
     "legendFormat": "average"
    }
   ]
  }
 ]
}