global:
  scrape_interval: 15s

rule_files:

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          app: "prometheus"
  - job_name: "backend"
    static_configs:
      - targets: ["host.docker.internal:8080"]
        labels:
          app: "backend"
  - job_name: "frontend"
    static_configs:
      - targets: ["host.docker.internal:5000"]
        labels:
          app: "frontend"
