package k8s

import (
       "github.com/prometheus/client_golang/prometheus"
)

// Describes the number of K8s containers that are currently in a state for a given reason.
type ContainerStatusReason struct {
     *prometheus.GaugeVec
     extra ContainerStatusReasonExtra
}



func NewContainerStatusReason() ContainerStatusReason {
     labels := []string{AttrContainerStatusReason("").Key(),}
     return ContainerStatusReason{ 
        GaugeVec: prometheus.NewGaugeVec(prometheus.GaugeOpts{
            Name: "k8s_container_status_reason",
            Help: "Describes the number of K8s containers that are currently in a state for a given reason.",
     }, labels)}
}

func (m ContainerStatusReason) With(containerStatusReason AttrContainerStatusReason,extras ...interface {}) prometheus.Gauge {
    return m.GaugeVec.WithLabelValues(containerStatusReason.Value(),)
}

// Deprecated: Use [ContainerStatusReason.With] instead
func (m ContainerStatusReason) WithLabelValues(lvs ...string) prometheus.Gauge {
    return m.GaugeVec.WithLabelValues(lvs...)
}



type ContainerStatusReasonExtra struct {

}



/*
State {
    name: "vec.go.j2",
    current_block: None,
    auto_escape: None,
    ctx: {
        "AttrExtra": "ContainerStatusReasonExtra",
        "Instr": "Gauge",
        "InstrMap": {
            "counter": "Counter",
            "gauge": "Gauge",
            "histogram": "Histogram",
            "updowncounter": "Gauge",
        },
        "Name": "container.status.reason",
        "Type": "ContainerStatusReason",
        "attributes": [
            {
                "brief": "The reason for the container state. Corresponds to the `reason` field of the: [K8s ContainerStateWaiting](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30/#containerstatewaiting-v1-core) or [K8s ContainerStateTerminated](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30/#containerstateterminated-v1-core)\n",
                "examples": [
                    "ContainerCreating",
                    "CrashLoopBackOff",
                    "CreateContainerConfigError",
                    "ErrImagePull",
                    "ImagePullBackOff",
                    "OOMKilled",
                    "Completed",
                    "Error",
                    "ContainerCannotRun",
                ],
                "name": "k8s.container.status.reason",
                "requirement_level": "required",
                "stability": "development",
                "type": {
                    "members": [
                        {
                            "brief": "The container is being created.",
                            "id": "container_creating",
                            "stability": "development",
                            "value": "ContainerCreating",
                        },
                        {
                            "brief": "The container is in a crash loop back off state.",
                            "id": "crash_loop_back_off",
                            "stability": "development",
                            "value": "CrashLoopBackOff",
                        },
                        {
                            "brief": "There was an error creating the container configuration.",
                            "id": "create_container_config_error",
                            "stability": "development",
                            "value": "CreateContainerConfigError",
                        },
                        {
                            "brief": "There was an error pulling the container image.",
                            "id": "err_image_pull",
                            "stability": "development",
                            "value": "ErrImagePull",
                        },
                        {
                            "brief": "The container image pull is in back off state.",
                            "id": "image_pull_back_off",
                            "stability": "development",
                            "value": "ImagePullBackOff",
                        },
                        {
                            "brief": "The container was killed due to out of memory.",
                            "id": "oom_killed",
                            "stability": "development",
                            "value": "OOMKilled",
                        },
                        {
                            "brief": "The container has completed execution.",
                            "id": "completed",
                            "stability": "development",
                            "value": "Completed",
                        },
                        {
                            "brief": "There was an error with the container.",
                            "id": "error",
                            "stability": "development",
                            "value": "Error",
                        },
                        {
                            "brief": "The container cannot run.",
                            "id": "container_cannot_run",
                            "stability": "development",
                            "value": "ContainerCannotRun",
                        },
                    ],
                },
            },
        ],
        "ctx": {
            "annotations": {
                "code_generation": {
                    "metric_value_type": "int",
                },
            },
            "attributes": [
                {
                    "brief": "The reason for the container state. Corresponds to the `reason` field of the: [K8s ContainerStateWaiting](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30/#containerstatewaiting-v1-core) or [K8s ContainerStateTerminated](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30/#containerstateterminated-v1-core)\n",
                    "examples": [
                        "ContainerCreating",
                        "CrashLoopBackOff",
                        "CreateContainerConfigError",
                        "ErrImagePull",
                        "ImagePullBackOff",
                        "OOMKilled",
                        "Completed",
                        "Error",
                        "ContainerCannotRun",
                    ],
                    "name": "k8s.container.status.reason",
                    "requirement_level": "required",
                    "stability": "development",
                    "type": {
                        "members": [
                            {
                                "brief": "The container is being created.",
                                "id": "container_creating",
                                "stability": "development",
                                "value": "ContainerCreating",
                            },
                            {
                                "brief": "The container is in a crash loop back off state.",
                                "id": "crash_loop_back_off",
                                "stability": "development",
                                "value": "CrashLoopBackOff",
                            },
                            {
                                "brief": "There was an error creating the container configuration.",
                                "id": "create_container_config_error",
                                "stability": "development",
                                "value": "CreateContainerConfigError",
                            },
                            {
                                "brief": "There was an error pulling the container image.",
                                "id": "err_image_pull",
                                "stability": "development",
                                "value": "ErrImagePull",
                            },
                            {
                                "brief": "The container image pull is in back off state.",
                                "id": "image_pull_back_off",
                                "stability": "development",
                                "value": "ImagePullBackOff",
                            },
                            {
                                "brief": "The container was killed due to out of memory.",
                                "id": "oom_killed",
                                "stability": "development",
                                "value": "OOMKilled",
                            },
                            {
                                "brief": "The container has completed execution.",
                                "id": "completed",
                                "stability": "development",
                                "value": "Completed",
                            },
                            {
                                "brief": "There was an error with the container.",
                                "id": "error",
                                "stability": "development",
                                "value": "Error",
                            },
                            {
                                "brief": "The container cannot run.",
                                "id": "container_cannot_run",
                                "stability": "development",
                                "value": "ContainerCannotRun",
                            },
                        ],
                    },
                },
            ],
            "brief": "Describes the number of K8s containers that are currently in a state for a given reason.",
            "entity_associations": [
                "k8s.container",
            ],
            "id": "metric.k8s.container.status.reason",
            "instrument": "updowncounter",
            "lineage": {
                "attributes": {
                    "k8s.container.status.reason": {
                        "inherited_fields": [
                            "brief",
                            "examples",
                            "note",
                            "stability",
                        ],
                        "locally_overridden_fields": [
                            "requirement_level",
                        ],
                        "source_group": "registry.k8s",
                    },
                },
                "provenance": {
                    "path": "https://github.com/open-telemetry/semantic-conventions.git[model]/k8s/metrics.yaml",
                    "registry_id": "main",
                },
            },
            "metric_name": "k8s.container.status.reason",
            "note": "All possible container state reasons will be reported at each time interval to avoid missing metrics.\nOnly the value corresponding to the current state reason will be non-zero.\n",
            "root_namespace": "k8s",
            "stability": "development",
            "type": "metric",
            "unit": "{container}",
        },
        "for_each_attr": <macro for_each_attr>,
        "module": "github.com/ArthurSens/demo-weaver-for-dashboarding/dashboards",
    },
    env: Environment {
        globals: {
            "concat_if": weaver_forge::extensions::util::concat_if,
            "cycler": minijinja_contrib::globals::cycler,
            "debug": minijinja::functions::builtins::debug,
            "dict": minijinja::functions::builtins::dict,
            "joiner": minijinja_contrib::globals::joiner,
            "namespace": minijinja::functions::builtins::namespace,
            "params": {
                "params": {},
            },
            "range": minijinja::functions::builtins::range,
            "template": {},
        },
        tests: [
            "!=",
            "<",
            "<=",
            "==",
            ">",
            ">=",
            "array",
            "boolean",
            "defined",
            "deprecated",
            "divisibleby",
            "endingwith",
            "enum",
            "enum_type",
            "eq",
            "equalto",
            "escaped",
            "even",
            "experimental",
            "false",
            "filter",
            "float",
            "ge",
            "greaterthan",
            "gt",
            "in",
            "int",
            "integer",
            "iterable",
            "le",
            "lessthan",
            "lower",
            "lt",
            "mapping",
            "ne",
            "none",
            "number",
            "odd",
            "safe",
            "sameas",
            "sequence",
            "simple_type",
            "stable",
            "startingwith",
            "string",
            "template_type",
            "test",
            "true",
            "undefined",
            "upper",
        ],
        filters: [
            "abs",
            "acronym",
            "ansi_bg_black",
            "ansi_bg_blue",
            "ansi_bg_bright_black",
            "ansi_bg_bright_blue",
            "ansi_bg_bright_cyan",
            "ansi_bg_bright_green",
            "ansi_bg_bright_magenta",
            "ansi_bg_bright_red",
            "ansi_bg_bright_white",
            "ansi_bg_bright_yellow",
            "ansi_bg_cyan",
            "ansi_bg_green",
            "ansi_bg_magenta",
            "ansi_bg_red",
            "ansi_bg_white",
            "ansi_bg_yellow",
            "ansi_black",
            "ansi_blue",
            "ansi_bold",
            "ansi_bright_black",
            "ansi_bright_blue",
            "ansi_bright_cyan",
            "ansi_bright_green",
            "ansi_bright_magenta",
            "ansi_bright_red",
            "ansi_bright_white",
            "ansi_bright_yellow",
            "ansi_cyan",
            "ansi_green",
            "ansi_italic",
            "ansi_magenta",
            "ansi_red",
            "ansi_strikethrough",
            "ansi_underline",
            "ansi_white",
            "ansi_yellow",
            "attr",
            "attribute_id",
            "attribute_namespace",
            "attribute_registry_file",
            "attribute_registry_namespace",
            "attribute_registry_title",
            "attribute_sort",
            "batch",
            "body_fields",
            "bool",
            "camel_case",
            "camel_case_const",
            "capitalize",
            "capitalize_first",
            "chain",
            "comment",
            "comment_with_prefix",
            "count",
            "d",
            "default",
            "dictsort",
            "e",
            "enum_type",
            "escape",
            "filesizeformat",
            "first",
            "flatten",
            "float",
            "groupby",
            "indent",
            "instantiated_type",
            "int",
            "items",
            "join",
            "kebab_case",
            "kebab_case_const",
            "last",
            "length",
            "lines",
            "list",
            "lower",
            "lower_case",
            "map",
            "map_text",
            "markdown_to_html",
            "max",
            "metric_namespace",
            "min",
            "not_required",
            "pascal_case",
            "pascal_case_const",
            "pluralize",
            "pprint",
            "print_member_value",
            "regex_replace",
            "reject",
            "rejectattr",
            "replace",
            "required",
            "reverse",
            "round",
            "safe",
            "screaming_kebab_case",
            "screaming_snake_case",
            "screaming_snake_case_const",
            "select",
            "selectattr",
            "slice",
            "snake_case",
            "snake_case_const",
            "sort",
            "split",
            "split_id",
            "string",
            "striptags",
            "sum",
            "title",
            "title_case",
            "tojson",
            "toyaml",
            "trim",
            "truncate",
            "type_mapping",
            "unique",
            "upper",
            "upper_case",
            "urlencode",
        ],
        templates: [
            "vec.go.j2",
        ],
    },
}
*/